# Needed since this subdir is symlinked in the main Kernel tree
# without this our samsung subdir is NOT cleaned.
clean-files := built-in.o

obj-$(CONFIG_MUIC_SAMSUNG_IFPMIC)	+= ifconn/
obj-$(CONFIG_MUIC_SAMSUNG_IFPMIC)	+= muic/
