# SPDX-License-Identifier: GPL-2.0
snd-soc-dp_dma-objs := dp_dma.o

obj-$(CONFIG_SND_SOC_SAMSUNG_DISPLAYPORT) += snd-soc-dp_dma.o
obj-$(CONFIG_SND_SOC_SAMSUNG_ABOX) += abox/
obj-$(CONFIG_SND_SOC_SAMSUNG_MAILBOX) += vts/
obj-$(CONFIG_SND_SOC_SAMSUNG_SLIF) += slif/

obj-$(CONFIG_SND_SOC_SAMSUNG_EXYNOS8845_SOUND) += exynos8845_sound.o
obj-$(CONFIG_SND_SOC_SAMSUNG_EXYNOS8845_AUDIO) += exynos8845_audio.o

obj-$(CONFIG_SND_SOC_SAMSUNG_AUDIO) += sec_audio_sysfs.o sec_audio_debug.o
