# SPDX-License-Identifier: GPL-2.0
#
# Makefile for multifunction miscellaneous devices for samsung pmic
#

obj-$(CONFIG_CHARGER_S2MF301)   		+= s2mf301_charger.o
obj-$(CONFIG_FUELGAUGE_S2MF301) 		+= s2mf301_fuelgauge.o
obj-$(CONFIG_PM_S2MF301)  			+= s2mf301_pmeter.o
obj-$(CONFIG_TOP_S2MF301)  			+= s2mf301_top.o
obj-$(CONFIG_MANAGER_S2M_CHARGER)   		+= s2m_chg_manager.o
obj-$(CONFIG_SYSFS_S2MF301)   			+= ifpmic_class.o
