# SPDX-License-Identifier: GPL-2.0-only

# ACPM
obj-$(CONFIG_EXYNOS_ACPM)		+= acpm/

# CAL
obj-$(CONFIG_CAL_IF)            	+= cal-if/

# DEBUG
obj-$(CONFIG_EXYNOS_DEBUG)		+= debug/

# Exynos Isolated CryptoManager
obj-$(CONFIG_EXYNOS_ICM)		+= exynos-icm.o

# Exynos Samsung Secure Platform
obj-$(CONFIG_EXYNOS_SSP)        	+= exynos-ssp.o

obj-$(CONFIG_EXYNOS_PMU_IF)		+= exynos-pmu-if.o

# Exynos WoW
obj-$(CONFIG_EXYNOS_WOW)       		+= exynos-wow.o

# CPIF
obj-$(CONFIG_EXYNOS_MODEM_IF)		+= cpif/

# Exynos Chipid V2
obj-$(CONFIG_EXYNOS_CHIPID_V2)		+= exynos-chipid_v2.o

# Exynos CryptoManager
obj-$(CONFIG_EXYNOS_CRYPTOMANAGER)	+= exynos-cm.o

# DVFS Manager
obj-y					+= dm/

# ECT
obj-$(CONFIG_ECT)               	+= ect_parser/

obj-$(CONFIG_EXYNOS_ESCAV2)		+= esca_v2/

obj-$(CONFIG_EXYNOS_PD)			+= exynos-pd/

obj-$(CONFIG_EXYNOS_PM) 		+= exynos-pm/

# GNSSIF
obj-$(CONFIG_EXYNOS_GNSS_IF)		+= gnssif/
obj-$(CONFIG_EXYNOS_GNSS_IF_SPI)       	+= gnssif_spi/

# EXYNOS_PM_QOS
obj-$(CONFIG_EXYNOS_PM_QOS)		+= pm_qos/

# Profiler Multi IP Governor
obj-$(CONFIG_EXYNOS_MAIN_PROFILER)	+= profiler/

# Exynos EL2
obj-$(CONFIG_EXYNOS_EL2)		+= exynos-el2.o

# Exynos S2MPU
obj-$(CONFIG_EXYNOS_S2MPU)		+= exynos-s2mpu.o

# Exynos Hypervisor
obj-$(CONFIG_EXYNOS_HYP)		+= exynos-hyp/

# Exynos MCINFO
obj-$(CONFIG_EXYNOS_MCINFO)             += exynos-mcinfo.o

# SDM
obj-$(CONFIG_EXYNOS_SDM)		+= exynos-sdm.o
