# SPDX-License-Identifier: GPL-2.0-only

# ACPM
obj-$(CONFIG_EXYNOS_ACPM)		+= acpm/

# CAL
obj-$(CONFIG_CAL_IF)            	+= cal-if/

# DEBUG
obj-$(CONFIG_EXYNOS_DEBUG)		+= debug/

# Exynos Isolated CryptoManager
obj-$(CONFIG_EXYNOS_ICM)		+= exynos-icm.o

# Exynos Samsung Secure Platform
obj-$(CONFIG_EXYNOS_SSP)        	+= exynos-ssp.o

obj-$(CONFIG_EXYNOS_PMU_IF)		+= exynos-pmu-if.o

# Exynos WoW
obj-$(CONFIG_EXYNOS_WOW)       		+= exynos-wow.o

# CPIF
obj-$(CONFIG_EXYNOS_MODEM_IF)		+= cpif/

# Exynos Chipid V2
obj-$(CONFIG_EXYNOS_CHIPID_V2)		+= exynos-chipid_v2.o

# Exynos CryptoManager
obj-$(CONFIG_EXYNOS_CRYPTOMANAGER)	+= exynos-cm.o

# DVFS Manager
obj-y					+= dm/

# ECT
obj-$(CONFIG_ECT)               	+= ect_parser/
