# SPDX-License-Identifier: GPL-2.0-only

# ACPM
obj-$(CONFIG_EXYNOS_ACPM)		+= acpm/

# CAL
obj-$(CONFIG_CAL_IF)            	+= cal-if/

# DEBUG
obj-$(CONFIG_EXYNOS_DEBUG)		+= debug/

# Exynos Isolated CryptoManager
obj-$(CONFIG_EXYNOS_ICM)		+= exynos-icm.o

# Exynos Samsung Secure Platform
obj-$(CONFIG_EXYNOS_SSP)        	+= exynos-ssp.o
