dtb-y += m56x_swa_ins_w00_r04.dtbo
dtb-y += m56x_swa_ins_w00_r03.dtbo
dtb-y += m56x_swa_ins_w00_r02.dtbo
dtb-y += m56x_swa_ins_w00_r01.dtbo
dtb-y += m56x_swa_ins_w00_r00.dtbo
# SPDX-License-Identifier: GPL-2.0
always-y	:= $(dtb-y) $(dtbo-y)
clean-files	:= *.dtb *.dtbo
